Hw2
KatyaKos/software_design pull request #2
Opened 2018-05-31 01:13 UTC by KatyaKos

2018-06-02 12:27 UTC, yurii-litvinov requested changes
- Лучше было сделать пуллреквест в ветку с CLI, чтобы было видно, что пришлось поменять.
- Не собирается: `Grep.kt: (3, 12): Unresolved reference: xenomachina`
- Ссылки на JUnit тоже нет, кстати
- Непонятное сообщение об ошибке:
```
grep -A plugin build.gradle.kts
For input string: "plugin"
```

2018-06-02 12:27 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/katyakos/commands/CommandFactory.kt
> +import jdk.nashorn.internal.runtime.regexp.joni.Syntax.Grep
У меня такого нету, не собирается :)

2018-06-02 13:06 UTC, KatyaKos commented
Ошибку сделала нормальной. Что с библиотеками не знаю, у меня все нормально. Может опять .gitignore что-то сожрал. Поправила на всякий случай.
@yurii-litvinov

2018-06-02 14:40 UTC, yurii-litvinov requested changes
Не, гит тут ни при чём. Библиотеки же у Вас нигде не подключаются. Их надо в build.gradle.kts вписать. И пропишите ещё заодно туда, пожалуйста, 
```
plugins {
    java
}
```
А то у меня даже не хочет прочитать файл сборки :) У Вас-то всё нормально, потому что у Вас проект в IDEA, в котором все заввисимости прописаны, но про него никто, кроме Вашей машины, не знает (и правильно). Travis помог бы решать такие проблемы в зародыше.

2018-06-03 12:53 UTC, KatyaKos commented
Вроде как починила. @yurii-litvinov

2018-06-03 13:30 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена

2018-06-03 13:32 UTC, merged